add command and link for elasticsearch
comses/comses.net pull request #619
Opened 2023-02-19 04:58 UTC by CharlesSheelam

This pull request updates the environment setup instructions on the readme.md file,  and adds some additional info for step 3.

2023-02-23 06:25 UTC, alee requested changes
Hi Charles, thanks for the PR! Got a few minor text changes to add to this PR, but you should also ensure that [maintainers can edit your PR / branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so we can help you get changes merged.

2023-02-23 06:25 UTC, alee commented on README.md
> +3. Add `vm.max_map_count=262144` to `/etc/sysctl.d/99-docker.conf` for elasticsearch. Access the file with the command : (`$ sudo nano /etc/sysctl.d/99-docker.conf`). More info on (https://www.elasti
How about something like:

3. Create or update a file, `/etc/sysctl.d/99-docker.conf` with the line `vm.max_map_count=262144` so [elasticsearch can run properly](https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html). You can create / access the file with an invocation like `$ sudo nano /etc/sysctl.d/99-docker.conf` and following the in-terminal instructions to save and exit.

2023-02-25 02:31 UTC, CharlesSheelam commented
Thanks Allen! Going to make those changes now, also will remember to switch on allow edits by maintainers for the future.

2023-02-28 08:33 UTC, alee reviewed
Looks like the link to the actual additional context got lost in the subsequent commits but I'll go ahead and squash & merge this and manually the docs changes to the README so we can get to actual coding

2023-02-28 08:33 UTC, merged