Add manual "mark spam" button for admins
comses/comses.net pull request #750
Opened 2024-08-06 20:55 UTC by ldwiyono

Added a manual "Mark spam" button as a template macro for admins to update ModeratedContent (Events, Jobs, Codebases) as spam. Possible further additions might be adding a notes field for users to add further details about the spam submission? Resolves comses/planning/issue/255.

Current appearance on desktop for events:
![image](https://github.com/user-attachments/assets/fea3e704-a97f-49c3-87c4-f187e4bd9f7b)

Please let me know about any feedback on this pull request or the button's functionality.

2024-08-06 22:51 UTC, sgfost commented
I'll test it out to make sure but the code LGTM, thanks Luke. The commits can be cleaned up, I guess just merged into 1 since the other 5 are adding/reverting test stuff. You can do this with an interactive rebase (can show you this tomorrow if you don't do it before)

In the meantime, the notes field might be a good addition. Should be fairly straightforward--just adding a textarea to the form and retrieving it from the request data

2024-08-07 01:20 UTC, alee requested changes
Good work! A few git issues however that must be addressed:

1. don't submit a PR from your main branch. Create a new feature branch and set up your commits and changesets there. Otherwise you will run into problems keeping your main branch properly synced up with upstream
2. keep your git history clean, we will only accept PRs that have a clean, linear history of relevant commits. In this case you can squash them all into a single commit but for the future you'll probably want to develop a better conceptual model of how git works and how to maintain a clean commit history: https://about.gitlab.com/blog/2020/11/23/keep-git-history-clean-with-interactive-rebase/

I don't think we need the "manually" part of the manually-mark-spam viewset method and corresponding endpoint. Let's leave it as "mark_spam" / "library:codebase-mark-spam"

2024-08-07 06:42 UTC, ldwiyono commented
I've squashed all the commits into one, including the "manually" name change you requested. Would you like me to close this pull request and open a new one from a non-main branch?

2024-08-07 20:37 UTC, closed without merging

2024-08-08 00:13 UTC, ldwiyono commented
Hi, I wanted to check before I opened a new pull request: does this look okay for the added notes field?
<img width="981" alt="image" src="https://github.com/user-attachments/assets/d9fee57b-6846-436d-858e-819586856e85">

2024-08-08 01:43 UTC, sgfost commented
use the bootstrap form classes for the styling https://getbootstrap.com/docs/5.0/forms/overview/

no need to hold off on the PR though